config/routes.rb
Rails.application.routes.draw do

  root                'static_pages#home'
  get 'help'      =>  'static_pages#help'
  get 'about'     =>  'static_pages#about'
  get 'contact'   =>  'static_pages#contact'
  get 'signup'    =>  'users#new'
  get 'login'     =>  'sessions#new'
  post 'login'    =>  'sessions#create'
  delete 'logout'   =>  'sessions#destroy'

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base

# Validations
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: EMAIL_REGEX }, uniqueness: {case_sensitive: false}
  validates :password, length: { minimum: 6 }, allow_blank: true

  before_save { self.email.downcase! }
# Adds password and password confirmation
  has_secure_password

  attr_accessor :remember_token

  # Generate and update the remember digest
  def remember
    # store virtually the new token
    self.remember_token = User.new_token
    # save the hash digest of the token on the database
    self.update_attribute(:remember_digest, User.digest(self.remember_token))
  end

  def forget
    self.update_attribute(:remember_digest, nil)
  end

  # Check if the remember_token passed is the same of
  # the stored on the database
  def authenticated?(remember_token)
    return false if self.remember_digest.nil?
    BCrypt::Password.new(self.remember_digest) == remember_token
  end


  # Class methods
  # encrypt the string and return its hash digest
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Generates a random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # For user log un handle
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      #hadle successful login
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      # if the user tried to access a protected page before
      # redirect him to this page
      redirect_back_or user
      # rails automatically converts redirect_to user to
      # named route user_url(user)
    else
      # create a error message and display
      flash.now[:danger] = "invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Social Net #{@user.name}"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:success] = "#{user.name} deleted"
    redirect_to users_url
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        # store the URL the user is trying to access
        # and after login, redirect him to this URL
        store_location
        flash[:danger] = 'Please, log in.'
        redirect_to login_url
      end
    end

    def admin_user
      if !current_user.admin?
        flash['danger'] = 'You do not have admin privileges'
        redirect_to(root_url)
      end
    end

    def correct_user
      @user = User.find(params[:id])
      if !current_user?(@user)
        flash[:danger] = "You don't have authorization to update this user"
        redirect_to(root_url) unless current_user?(@user)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = 'Social Net'
    if page_title.empty?
      base_title
    else
      "#{page_title} | Social Net"
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper


  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def remember(user)
    # From now on, we can access the remember_token
    # virtual attribute from the user because the remember
    # method generated a new remember token and saved the
    # hash digest of the token into the database
    user.remember
    # send securely the user id to the user browser
    cookies.permanent.signed[:user_id] = user.id
    # send the remember token to the user browser
    # for future authentication
    cookies.permanent[:remember_token] = user.remember_token
  end

  # delete the user data from persistent session
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    # Check if the user is logged in using session
    # in the case that he has chosen to not be remembered
    if user_id = session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
      # otherwise, if the user selected to be remembered
      # we are going to look up in the cookies
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        # if the user is valid
        # we can log in him(using sessions)
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.rubyonrails.org/">The Ruby On Rails Framework</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header  class="navbar navbar-fixed-top" id="main-header">
  <div class="container">
    <%= link_to "Social Net", root_path, id: 'logo' %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Help', help_path %></li>

        <% if logged_in? %>
          <li><%=  link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Profile', current_user %></li>
              <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log in', login_path %></li>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <%= yield %>

    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>



</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, 'error') %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h1>About</h1>

<p>About page</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact</h1>

<p>Contact form goes here</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Social Net</h1>
  <%= link_to "Sign up now!", signup_path, class: 'btn btn-lg btn-primary' %>
</div>

app/views/users/_fields.html.erb
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control'%>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to 'delete', user, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit') %>

<h1>Edit Profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit 'Update profile', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%provide(:title, 'All Users') %>

<h1>All Users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>

<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f  %>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for(@user) %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>